# Generated by Django 4.2.7 on 2023-11-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.CharField(max_length=30),
        ),
    ]
