# Generated by Django 4.2.7 on 2023-12-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_user_birth_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=1024)),
            ],
        ),
    ]
