# Generated by Django 4.2.7 on 2023-12-06 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_adminuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
