# Generated by Django 4.2.7 on 2023-12-06 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_delete_adminuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
