# Generated by Django 4.2.7 on 2023-12-28 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='year',
            new_name='pubyear',
        ),
    ]
