# Generated by Django 4.2.7 on 2023-12-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_year_book_pubyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='reviews',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
