# Generated by Django 4.2.7 on 2023-12-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_book_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='reviews_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
