# Generated by Django 4.2.8 on 2023-12-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_book_reviews_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='default.png', upload_to='books/'),
        ),
    ]
