# Generated by Django 4.2.8 on 2023-12-28 12:42

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_book_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='default.png', upload_to=api.models.upload_to),
        ),
    ]
