# Generated by Django 4.2.8 on 2023-12-28 14:31

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_book_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='default_user.svg', upload_to=api.models.upload_to),
        ),
    ]
