# Generated by Django 4.2.8 on 2023-12-28 14:39

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(default='books/default.png', upload_to=api.models.upload_to),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='users/default_user.svg', upload_to=api.models.upload_to),
        ),
    ]
